version: "3.3"

services:

    api:
        container_name: "api"
        build: "api/."
        restart: "always"
        ports:
            - "8081:5000"

    app:
        container_name: "app"
        build: "app/."
        restart: "always"
        depends_on:
            - "api"
        ports:
            - "8080:3000"